# Generated by Django 3.2.7 on 2022-06-10 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Information', models.CharField(max_length=256)),
                ('photo', models.FileField(blank=True, upload_to='Notifications/')),
                ('Action_required', models.CharField(max_length=256)),
                ('Raised_by', models.CharField(max_length=256)),
                ('Status', models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=256, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
